
CONFIG = {
    'INPUT_FILENAME': 'export_01_sample.csv',
    'OUTPUT_FILENAME': 'data_prepped_for_nb.csv',
    'EXPECTED_ROW_COUNT': 1000,  # 93954,
    'EXPECTED_COL_COUNT': 297,
    'DATA_DIRECTORY': 'data',
    'CUSTOM_FIELDS_DIRECTORY': 'customFieldValues',
    'META_DATA_GSHEET_NAME': 'JCF - Source to Target Mapping',
    'GOOGLE_API_KEY_FILE': 'jcf_google_api_key_file.json',
    'GOOGLE_API_SCOPE': [
        'https://spreadsheets.google.com/feeds',
        'https://www.googleapis.com/auth/drive'],
    'META_DATA_TMP_FILENAME': 'meta_data.csv',
    # 'COLUMN_MAPPINGS': {
    #     "Prefix": "prefix",
    #     "First Name": "first_name",
    #     "Last Name": "last_name",
    #     "Address 1": "address1",
    #     "Address 2": "address2",
    #     "City": "city",
    #     "Zip": "zip",
    #     "County": "county",
    #     "Country": "country",
    #     "Employer": "employer",
    #     "Occupation": "occupation",
    #     "Email": "email",
    #     "Home Phone": "phone_number",
    #     "Work Phone": "work_phone_number",
    #     "Join Date": "created_at",
    #     "Are you a person of faith?": "religion",
    #     "2018 Partner Resources:Name of Organisation": "organisation",
    #     "Amnesty Sign up:Group name": "organisation",
    #     "Girlguiding Sign Up:Group Name": "organisation",
    #     "Girlguiding Sign Up:County": "county",
    #     "Girlguiding Sign Up:If you'd like us to post you an ideas pack, please fill out your address details:": "address",
    #     "Organisational/company sign up:Name of Organisation": "last_name",
    #     "Organisational/company sign up:Region": "county",
    #     "Organisational/company sign up:Organisation Website": "website",
    #     "Schools 2018:Key Contact Name": "first_name, last_name",
    #     "Schools 2018:Region": "county",
    #     "Scouts Events:Scout Group:": "organisation",
    #     "Scouts Events:Scouts County": "county",
    #     "Scouts Events:If you'd like us to post you an ideas pack, please fill out your address details:": "address",
    #     "Scouts PackSign Up:Scout Group:": "organisation",
    #     "Scouts PackSign Up:Scouts County": "county",
    #     "Salesforce ID": "salesforce_id",
    #     "Unique Constituent ID": "bsd_id",
    #     "Parliamentary Constituency (U.K.)": "Westminster Parliamentary Constituency",
    #     "Source": "source",
    #     "Did the Great Get Together make you feel more or less hopeful about Britain?": "17_survey_hopeful",
    #     "Did you meet anyone new at your get together?": "17_survey_meet",
    #     "Do you have any children?": "parent?",
    #     "Do you know most of your neighbours?": "17_survey_neighbours?",
    #     "Do you think we should do The Great Get Together again next year?": "17_survey_ggt_again?",
    #     "First of all, how were you involved with The Great Get Together?": "17_survey_role",
    #     "Had you ever organised a similar event before?": "17_survey_similiar_event?",
    #     "How do you feel about Britain at the moment?": "17_survey_feel_britain",
    #     "How old are you?": "17_survey_age",
    #     "If The Great Get Together happens next year, what should we do differently and what should we keep the same?": "17_different_next_yr",
    #     "None of our ideas take your fancy? No problem -- is there something you had in mind?": "17_event_ideas",
    #     "What is the one thing that would most improve your local community?": "18_improve_community?",
    #     "What type of pack would you like?": "18_pre_survey_pack_type",
    #     "Which of these activities appeals to you most?": "18_pre_survey_activities",
    #     "Which of these is closest to your thinking?": "18_pre_survey_impact ",
    #     "Will you pledge to do something -- big or small -- to bring your local community together on the weekend of 17 and 18 June?": "18_pre_survey_pledge",
    #     "2018 Supporter Pack:Are you planning on attending or organising an event?": "18_pre_survey_organising?",
    #     "2018 Supporter Pack:What do you think you might like to attend?": "18_pre_survey_event_attend",
    #     "2018 Supporter Pack:What kind of Get Together will you organise?": "18_pre_survey_event_type",
    #     "2018 Supporter Pack:Organising something else? Let us know what!": "18_pre_survey_different",
    #     "Organisational/company sign up:What is your reach?": "organisation_reach",
    #     "Organisational/company sign up:What bracket does your organisation fit into?": "organisation_type",
    #     "PACK - Form 2 - Who With:Who would you most like to have a get together with? Letting us know will mean we can give you better support setting up your event.": "pair_request",
    #     "PLEDGE 1 TGGT Website:Will you pledge to do something -- big or small -- to bring your local community together?": "18_pre_survey_pledge",
    #     "PLEDGE 2 TGGT Website:Which of these activities appeals to you most?": "18_pre_survey_activities",
    #     "PLEDGE to get involved with TGGT:Will you pledge to do something -- big or small -- to bring your local community together on the weekend of 17 and 18 June?": "18_pre_survey_pledge",
    #     "PLEDGE to get involved with TGGT:Which of these activities appeals to you most?": "18_pre_survey_activities",
    #     "Pledgers Survey:The Great Get Together would love to use what you're doing to inspire others. Anything on social media or in the press will just use your first name and location and we won't share your details with any journalists.<br>Please tick this box if you would NOT like the information you've provided here to be used in this way.": "social_share_permission",
    #     "State": "county",
    #     "Amnesty Sign up:If you'd like us to post you an ideas pack, please fill out your address details:": "address",
    #     "Birmingham feedback:Which of the following areas of the Great Get Together interest you the most?": "NOT MAPPED",
    #     "Brum 31 October:Please remind us, what was the get together event that you helped to organise?": "NOT MAPPED",
    #     "cardiff feedback:For you, what was the best thing about the meeting?": "NOT MAPPED",
    #     "Christmas Get Together Feedback:How many people took part in your #MincePieMoments?": "NOT MAPPED",
    #     "Christmas Sign Up:Checkbox": "NOT MAPPED",
    #     "EVENT London meeting 18 October:Please remind us, what was the get together event that you helped to organise?": "NOT MAPPED",
    #     "PACK - Form 1 - Details:What type of pack would you like?": "NOT MAPPED",
    #     "Postal Pack 2018:Would you prefer your pack in the post or by email?": "NOT MAPPED",
    #     "Survey for More In Common Groups:Can you describe yourself in approximately 140 characters?": "NOT MAPPED",
    # },
    # 'INSCOPE_COLUMNS': [
    #     "Prefix",
    #     "First Name",
    #     "Last Name",
    #     "Address 1",
    #     "Address 2",
    #     "City",
    #     "Zip",
    #     "County",
    #     "Country",
    #     "Employer",
    #     "Occupation",
    #     "Email",
    #     "Home Phone",
    #     "Work Phone",
    #     "Join Date",
    #     "Are you a person of faith?",
    #     "2018 Partner Resources:Name of Organisation",
    #     "Amnesty Sign up:Group name",
    #     "Girlguiding Sign Up:Group Name",
    #     "Girlguiding Sign Up:County",
    #     "Girlguiding Sign Up:If you'd like us to post you an ideas pack, please fill out your address details:",
    #     "Organisational/company sign up:Name of Organisation",
    #     "Organisational/company sign up:Region",
    #     "Organisational/company sign up:Organisation Website",
    #     "Schools 2018:Key Contact Name",
    #     "Schools 2018:Region",
    #     "Scouts Events:Scout Group:",
    #     "Scouts Events:Scouts County",
    #     "Scouts Events:If you'd like us to post you an ideas pack, please fill out your address details:",
    #     "Scouts PackSign Up:Scout Group:",
    #     "Scouts PackSign Up:Scouts County",
    #     "Salesforce ID",
    #     "Unique Constituent ID",
    #     "Parliamentary Constituency (U.K.)",
    #     "Source",
    #     "Did the Great Get Together make you feel more or less hopeful about Britain?",
    #     "Did you meet anyone new at your get together?",
    #     "Do you have any children?",
    #     "Do you know most of your neighbours?",
    #     "Do you think we should do The Great Get Together again next year?",
    #     "First of all, how were you involved with The Great Get Together?",
    #     "Had you ever organised a similar event before?",
    #     "How do you feel about Britain at the moment?",
    #     "How old are you?",
    #     "If The Great Get Together happens next year, what should we do differently and what should we keep the same?",
    #     "None of our ideas take your fancy? No problem -- is there something you had in mind?",
    #     "What is the one thing that would most improve your local community?",
    #     "What type of pack would you like?",
    #     "Which of these activities appeals to you most?",
    #     "Which of these is closest to your thinking?",
    #     "Will you pledge to do something -- big or small -- to bring your local community together on the weekend of 17 and 18 June?",
    #     "2018 Supporter Pack:Are you planning on attending or organising an event?",
    #     "2018 Supporter Pack:What do you think you might like to attend?",
    #     "2018 Supporter Pack:What kind of Get Together will you organise?",
    #     "2018 Supporter Pack:Organising something else? Let us know what!",
    #     "Organisational/company sign up:What is your reach?",
    #     "Organisational/company sign up:What bracket does your organisation fit into?",
    #     "PACK - Form 2 - Who With:Who would you most like to have a get together with? Letting us know will mean we can give you better support setting up your event.",
    #     "PLEDGE 1 TGGT Website:Will you pledge to do something -- big or small -- to bring your local community together?",
    #     "PLEDGE 2 TGGT Website:Which of these activities appeals to you most?",
    #     "PLEDGE to get involved with TGGT:Will you pledge to do something -- big or small -- to bring your local community together on the weekend of 17 and 18 June?",
    #     "PLEDGE to get involved with TGGT:Which of these activities appeals to you most?",
    #     "Pledgers Survey:The Great Get Together would love to use what you're doing to inspire others. Anything on social media or in the press will just use your first name and location and we won't share your details with any journalists.<br>Please tick this box if you would NOT like the information you've provided here to be used in this way.",
    #     "State",
    #     "Amnesty Sign up:If you'd like us to post you an ideas pack, please fill out your address details:",
    #     "Birmingham feedback:Which of the following areas of the Great Get Together interest you the most?",
    #     "Brum 31 October:Please remind us, what was the get together event that you helped to organise?",
    #     "cardiff feedback:For you, what was the best thing about the meeting?",
    #     "Christmas Get Together Feedback:How many people took part in your #MincePieMoments?",
    #     "Christmas Sign Up:Checkbox",
    #     "EVENT London meeting 18 October:Please remind us, what was the get together event that you helped to organise?",
    #     "PACK - Form 1 - Details:What type of pack would you like?",
    #     "Postal Pack 2018:Would you prefer your pack in the post or by email?",
    #     "Survey for More In Common Groups:Can you describe yourself in approximately 140 characters?"
    # ]
}
